# 项目元数据
[project]
name = "fc2-leak-detector"
version = "0.0.1"
description = "FC2流出检测器，用于查询和分析FC2视频流出状态"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "GPL-3.0-or-later" }
authors = [{ name = "soundstarrain" }]
maintainers = [{ name = "soundstarrain" }]
keywords = ["fc2", "video", "leakage", "detection"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: End Users/Desktop",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
dependencies = [
  "requests>=2.0.0",
  "beautifulsoup4>=4.4.0",
  "loguru>=0.5.0",
  "rich>=14.0.0",
  "typing-extensions>=4.0.0",
]

[project.urls]
"Homepage" = "https://github.com/FC2-Research-Club/FC2-Leak-Detector"
"Bug Reports" = "https://github.com/FC2-Research-Club/FC2-Leak-Detector/issues"
"Source" = "https://github.com/FC2-Research-Club/FC2-Leak-Detector"

[project.optional-dependencies]
dev = [
  "flake8==6.1.0",
  "pytest==8.3.5",
  "pytest-cov==6.1.1",
  "build==1.2",
  "wheel==0.46.0",
]


[build-system]
requires = [
  "hatchling==1.26.3",
] # Without a version spec, hatchling==1.27.0 is used which fails to publish. Ref: https://github.com/astral-sh/rye/issues/1446#issuecomment-2545154562
build-backend = "hatchling.build"


[tool.hatch.build.targets.wheel]
packages = ["src"]


[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"]
exclude = [
  ".git",
  "__pycache__",
  "build",
  "dist",
  "venv",
  ".venv",
  ".env",
  "env",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

[tool.coverage.run]
source = ["src"]
omit = ["tests/*"]
